title = "Joker@Minecraft ğŸ‡¨ğŸ‡³"
baseURL = "https://minecraft.jokerhub.cn"
languageCode = ""

theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "zh"
SectionPagesMenu = "main"

[pagination]
  pagerSize = 3

# googleAnalytics = ""
# enableRobotsTXT = false
# 
# [sitemap]
#   changefreq = "monthly"
#   priority = 0.5
#   filename = "sitemap.xml"
# 
[params]
  env = 'production'
  favicon = "favicon.ico"
  facebook = "https://www.facebook.com/profile.php?id=100018721351347"
  twitter = "https://twitter.com/w_z_z_1991"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCjZI4uZWSEt-bYFTbP0zB3A?view_as=subscriber"
  github = "https://github.com/OrzGeeker/OrzMC"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  wechat = ""
  qq = ""
  
  body_classes = "avenir bg-near-white"
  text_color = "black"
  cover_dimming_class = "bg-black-10"

  recent_copy = "æœ€è¿‘å‘å¸ƒ"
  recent_posts_number = 3
  read_more_copy = "é˜…è¯»å…¨æ–‡"
